/**
 * Zentrale Source-of-Truth fuer alle Blog-Posts.
 * - Blog-Uebersicht (`app/blog/page.tsx`) rendert daraus die Liste.
 * - Sitemap (`app/sitemap.ts`) nutzt `publishedAt` als `lastModified`.
 * - RSS-Feed (`app/blog/feed.xml/route.ts`) nutzt `publishedAt` + `excerpt` + `category`.
 *
 * Beim Anlegen eines neuen Blog-Posts: hier eintragen UND die zugehoerige
 * `app/blog/<slug>/page.tsx` erstellen. Damit sind sitemap, RSS und UI
 * automatisch konsistent.
 */

export type BlogPost = {
    slug: string;
    title: string;
    excerpt: string;
    category: string;
    readTime: string;
    /** Deutsche Datumsschreibung fuer die UI, z. B. "24. Maerz 2026". */
    publishDate: string;
    /** ISO 8601 (YYYY-MM-DD), wird fuer sitemap & RSS verwendet. */
    publishedAt: string;
    featured: boolean;
    image: string;
};

export const blogPosts: BlogPost[] = [
    {
        slug: 'google-bewertungen-kosmetikstudio',
        title: 'Google Bewertungen für Kosmetikstudios: So sammelst du mehr und bessere Rezensionen',
        excerpt: 'So sammelst du als Kosmetikstudio mehr Google-Bewertungen: erlaubte Methoden, der richtige Zeitpunkt, automatische Bewertungsanfragen und der Umgang mit negativer Kritik.',
        category: 'Marketing',
        readTime: '11 min',
        publishDate: '2. Juni 2026',
        publishedAt: '2026-06-02',
        featured: false,
        image: '/images/blog/google-business-kosmetik.jpg',
    },
    {
        slug: 'kassensystem-kosmetikstudio',
        title: 'Kassensystem für Kosmetikstudios: TSE-Pflicht, GoBD und die richtige Auswahl',
        excerpt: 'Kassensystem für dein Kosmetikstudio: Was TSE-Pflicht, GoBD und Belegausgabepflicht bedeuten, offene Ladenkasse vs. elektronische Kasse und worauf du bei der Auswahl achten solltest.',
        category: 'Business',
        readTime: '11 min',
        publishDate: '2. Juni 2026',
        publishedAt: '2026-06-02',
        featured: false,
        image: '/images/blog/kosmetikstudio-buchhaltung.jpg',
    },
    {
        slug: 'stornogebuehren-kosmetikstudio',
        title: 'Stornogebühren im Kosmetikstudio: So führst du ein Ausfallhonorar rechtssicher ein',
        excerpt: 'Stornogebühren im Kosmetikstudio rechtssicher einführen: Wann ein Ausfallhonorar erlaubt ist, sinnvolle Fristen und Höhe sowie eine klare Vorlage für deine Stornobedingungen.',
        category: 'Recht & Compliance',
        readTime: '9 min',
        publishDate: '1. Juni 2026',
        publishedAt: '2026-06-01',
        featured: false,
        image: '/images/blog/no-shows-reduzieren.jpg',
    },
    {
        slug: 'gutscheine-kosmetikstudio-verkaufen',
        title: 'Gutscheine im Kosmetikstudio verkaufen: Der unterschätzte Umsatz-Booster',
        excerpt: 'Gutscheine im Kosmetikstudio verkaufen: So steigerst du mit Geschenkgutscheinen den Umsatz, gewinnst neue Kundinnen und vermeidest typische rechtliche Fehler bei Gültigkeit und Buchhaltung.',
        category: 'Business',
        readTime: '9 min',
        publishDate: '1. Juni 2026',
        publishedAt: '2026-06-01',
        featured: false,
        image: '/images/blog/produktverkauf-guide.jpg',
    },
    {
        slug: 'terminbuchung-kosmetikstudio',
        title: 'Terminbuchung Kosmetikstudio: So läuft dein Kalender endlich rund',
        excerpt: 'Terminbuchung im Kosmetikstudio optimieren: weniger Ausfälle, bessere Auslastung und klarere Abläufe mit digitalem Buchungsprozess.',
        category: 'Organisation',
        readTime: '12 min',
        publishDate: '24. März 2026',
        publishedAt: '2026-03-24',
        featured: false,
        image: '/images/blog/terminkalender.png',
    },
    {
        slug: 'kundenkartei-kosmetik',
        title: 'Kundenkartei Kosmetik: Digital statt Zettelchaos',
        excerpt: 'Kundenkartei für Kosmetikstudios digital aufbauen: bessere Übersicht, schnellere Abläufe und saubere Dokumentation pro Kundin.',
        category: 'Digitalisierung',
        readTime: '11 min',
        publishDate: '24. März 2026',
        publishedAt: '2026-03-24',
        featured: false,
        image: '/images/blog/anamnese-digital.jpg',
    },
    {
        slug: 'behandlungsdokumentation-kosmetik',
        title: 'Behandlungsdokumentation Kosmetik: So dokumentierst du sicher und schnell',
        excerpt: 'Behandlungsdokumentation im Kosmetikstudio richtig aufsetzen: rechtssicher, übersichtlich und im Alltag schnell nutzbar.',
        category: 'Recht & Compliance',
        readTime: '12 min',
        publishDate: '24. März 2026',
        publishedAt: '2026-03-24',
        featured: false,
        image: '/images/blog/nisv-dokumentation.jpg',
    },
    {
        slug: 'schoenheitssalon-software',
        title: 'Schönheitssalon Software: Was 2026 wirklich wichtig ist',
        excerpt: 'Welche Schönheitssalon Software passt wirklich? Die wichtigsten Funktionen, typische Fehler und klare Auswahlkriterien für Studios.',
        category: 'Software',
        readTime: '8 min',
        publishDate: '24. März 2026',
        publishedAt: '2026-03-24',
        featured: false,
        image: '/images/blog/beste-kosmetikstudio-software-2026.jpg',
    },
    {
        slug: 'software-kosmetikinstitut',
        title: 'Software Kosmetikinstitut: So findest du die passende Lösung',
        excerpt: 'Software für Kosmetikinstitute im Vergleich: Welche Funktionen wirklich zählen und wie du typische Fehler bei der Umstellung vermeidest.',
        category: 'Digitalisierung',
        readTime: '7 min',
        publishDate: '24. März 2026',
        publishedAt: '2026-03-24',
        featured: false,
        image: '/images/blog/online-buchung-vorteile.jpg',
    },
    {
        slug: 'beste-kosmetikstudio-software-2026',
        title: 'Beste Kosmetikstudio Software 2026 - Der ultimative Vergleich',
        excerpt: 'Welche Software eignet sich am besten für dein Kosmetikstudio? Wir vergleichen die besten Lösungen 2026 nach Funktionen, Preis und Bedienung.',
        category: 'Software',
        readTime: '12 min',
        publishDate: '15. März 2026',
        publishedAt: '2026-03-15',
        featured: true,
        image: '/images/blog/beste-kosmetikstudio-software-2026.jpg',
    },
    {
        slug: 'no-shows-reduzieren-kosmetikstudio',
        title: 'No-Shows im Kosmetikstudio reduzieren: Was wirklich hilft',
        excerpt: 'Leere Stühle nerven. Mit Erinnerungen, Buchungsbestätigung und ein paar Kniffen senkst du verpasste Termine spürbar – ohne großen Aufwand.',
        category: 'Automatisierung',
        readTime: '6 min',
        publishDate: '8. Januar 2025',
        publishedAt: '2025-01-08',
        featured: false,
        image: '/images/blog/no-shows-reduzieren.jpg',
    },
    {
        slug: 'anamnese-formulare-digital-kosmetik',
        title: 'Anamnese digital: Formulare im Kosmetikstudio rechtssicher nutzen',
        excerpt: 'Anamnese und Einwilligung digital statt auf Papier. Was du beachten musst, damit es rechtssicher ist und im Alltag funktioniert.',
        category: 'Recht & Compliance',
        readTime: '5 min',
        publishDate: '5. Januar 2025',
        publishedAt: '2025-01-05',
        featured: false,
        image: '/images/blog/anamnese-digital.jpg',
    },
    {
        slug: 'google-business-profil-kosmetikstudio',
        title: 'Google Business Profil für Kosmetikstudios: Sichtbar werden',
        excerpt: 'Mit einem gepflegten Google-Profil findest du leichter neue Kundinnen. So richtest du es ein und nutzt es im Alltag.',
        category: 'Marketing',
        readTime: '5 min',
        publishDate: '28. Dezember 2024',
        publishedAt: '2024-12-28',
        featured: false,
        image: '/images/blog/google-business-kosmetik.jpg',
    },
    {
        slug: 'ki-kosmetikstudio-hautanalyse',
        title: 'KI im Kosmetikstudio: Hautanalyse der Zukunft',
        excerpt: 'Künstliche Intelligenz revolutioniert die Hautanalyse. Erfahre, wie KI-gestützte Tools dein Studio professioneller machen und Kunden begeistern - ohne Technik-Stress.',
        category: 'Digitalisierung',
        readTime: '11 min',
        publishDate: '22. Dezember 2024',
        publishedAt: '2024-12-22',
        featured: false,
        image: '/images/blog/ki-kosmetikstudio-hautanalyse.jpg',
    },
    {
        slug: 'anti-aging-trends-2024',
        title: 'Anti-Aging Trends 2024: Diese Behandlungen sind jetzt gefragt',
        excerpt: 'Von Micro-Needling bis hin zu personalisierten Peptid-Therapien - entdecke die neuesten Anti-Aging Trends, mit denen du dein Kosmetikstudio 2024 erfolgreich positionierst.',
        category: 'Fachkompetenz',
        readTime: '12 min',
        publishDate: '20. Dezember 2024',
        publishedAt: '2024-12-20',
        featured: true,
        image: '/images/blog/anti-aging-trends-2024.jpg',
    },
    {
        slug: 'wochenplanung-termine-kosmetikstudio',
        title: 'Wochenplanung im Kosmetikstudio: Termine im Griff',
        excerpt: 'Wie du deine Woche so planst, dass du genug Termine hast, aber nicht im Dauerstress. Praktische Tipps aus dem Studio-Alltag.',
        category: 'Organisation',
        readTime: '4 min',
        publishDate: '20. Dezember 2024',
        publishedAt: '2024-12-20',
        featured: false,
        image: '/images/blog/wochenplanung-termine.jpg',
    },
    {
        slug: 'kosmetikstudio-buchhaltung-steuern',
        title: 'Kosmetikstudio Buchhaltung: Was du steuerlich absetzen kannst',
        excerpt: 'Spare bis zu 40% Steuern mit der richtigen Buchhaltung. Alle Ausgaben, die du als Kosmetikstudio-Betreiberin absetzen kannst - plus praktische Tipps für den Alltag.',
        category: 'Business',
        readTime: '13 min',
        publishDate: '18. Dezember 2024',
        publishedAt: '2024-12-18',
        featured: false,
        image: '/images/blog/kosmetikstudio-buchhaltung.jpg',
    },
    {
        slug: 'email-marketing-kosmetikstudios',
        title: 'Email-Marketing für Kosmetikstudios: Kunden erfolgreich zurückgewinnen',
        excerpt: 'Mit strategischem Email-Marketing holst du verlorene Kunden zurück und steigerst deinen Umsatz um bis zu 40%. So baust du eine erfolgreiche Email-Strategie auf.',
        category: 'Marketing',
        readTime: '10 min',
        publishDate: '15. Dezember 2024',
        publishedAt: '2024-12-15',
        featured: true,
        image: '/images/blog/email-marketing-kosmetikstudios.jpg',
    },
    {
        slug: 'kundenbindung-kosmetikstudio-5-strategien',
        title: '5 bewährte Strategien für mehr Kundenbindung im Kosmetikstudio',
        excerpt: 'Entdecke die wirksamsten Methoden, um Kundinnen langfristig zu binden und die Wiederkehrrate zu erhöhen. Von personalisierten Behandlungen bis zur digitalen Nachbetreuung.',
        category: 'Kundenbindung',
        readTime: '8 min',
        publishDate: '15. Dezember 2024',
        publishedAt: '2024-12-15',
        featured: false,
        image: '/images/blog/kundenbindung-strategien.jpg',
    },
    {
        slug: 'dsgvo-datenschutz-kosmetikstudio',
        title: 'DSGVO im Kosmetikstudio: Datenschutz ohne Panik',
        excerpt: 'Kundendaten, Fotos, Anamnese – was du speichern darfst, was du brauchst und wie du DSGVO-konform bleibst.',
        category: 'Recht & Compliance',
        readTime: '6 min',
        publishDate: '14. Dezember 2024',
        publishedAt: '2024-12-14',
        featured: false,
        image: '/images/blog/dsgvo-kosmetikstudio.jpg',
    },
    {
        slug: 'hautanalyse-beratung-kosmetikstudio',
        title: 'Professionelle Hautanalyse: Der Schlüssel zu erfolgreichen Behandlungen',
        excerpt: 'Eine gründliche Hautanalyse ist die Basis jeder erfolgreichen Kosmetikbehandlung. 7-Schritte Prozess für professionelle Beratung und Kundenbindung.',
        category: 'Fachkompetenz',
        readTime: '8 min',
        publishDate: '12. Dezember 2024',
        publishedAt: '2024-12-12',
        featured: false,
        image: '/images/blog/hautanalyse-beratung.jpg',
    },
    {
        slug: 'online-buchungssystem-vorteile',
        title: 'Warum jedes Kosmetikstudio 2024 ein Online-Buchungssystem braucht',
        excerpt: 'Online-Buchungen sind kein Luxus mehr, sondern Notwendigkeit. Erfahre, wie du 30% mehr Termine generierst und deine Kundinnen begeisterst.',
        category: 'Digitalisierung',
        readTime: '6 min',
        publishDate: '10. Dezember 2024',
        publishedAt: '2024-12-10',
        featured: false,
        image: '/images/blog/online-buchung-vorteile.jpg',
    },
    {
        slug: 'erste-kundinnen-gewinnen-kosmetikstudio',
        title: 'Erste Kundinnen gewinnen: Tipps für neue Kosmetikstudios',
        excerpt: 'Neu eröffnet und noch wenig gebucht? So kommst du zu den ersten Terminen – ohne teures Marketing.',
        category: 'Marketing',
        readTime: '5 min',
        publishDate: '10. Dezember 2024',
        publishedAt: '2024-12-10',
        featured: false,
        image: '/images/blog/erste-kundinnen-gewinnen.jpg',
    },
    {
        slug: 'kosmetikstudio-eroeffnen-guide',
        title: 'Kosmetikstudio eröffnen: Der ultimative Guide für 2024',
        excerpt: 'Von der ersten Idee bis zur Eröffnung: Alle Schritte, Kosten und Tipps für dein erfolgreiches Kosmetikstudio. Praxiserprobt und rechtssicher.',
        category: 'Business',
        readTime: '15 min',
        publishDate: '8. Dezember 2024',
        publishedAt: '2024-12-08',
        featured: false,
        image: '/images/blog/kosmetikstudio-eroeffnen.jpg',
    },
    {
        slug: 'behandlungsdokumentation-nisv-konform',
        title: 'NiSV-konforme Behandlungsdokumentation: Was du wissen musst',
        excerpt: 'Seit der NiSV-Verordnung ist professionelle Dokumentation Pflicht. So dokumentierst du rechtssicher und effizient - ohne Mehraufwand.',
        category: 'Recht & Compliance',
        readTime: '10 min',
        publishDate: '5. Dezember 2024',
        publishedAt: '2024-12-05',
        featured: false,
        image: '/images/blog/nisv-dokumentation.jpg',
    },
    {
        slug: 'behandlungsraum-einrichten-kosmetikstudio',
        title: 'Behandlungsraum einrichten: Worauf es ankommt',
        excerpt: 'Licht, Stauraum, Hygiene – wie du deinen Behandlungsraum so gestaltest, dass du gut arbeitest und Kundinnen sich wohlfühlen.',
        category: 'Fachkompetenz',
        readTime: '4 min',
        publishDate: '5. Dezember 2024',
        publishedAt: '2024-12-05',
        featured: false,
        image: '/images/blog/behandlungsraum-einrichten.jpg',
    },
    {
        slug: 'mitarbeiterfuehrung-beauty-business',
        title: 'Mitarbeiterführung im Beauty-Business: So baust du ein Traumteam auf',
        excerpt: 'Erfolgreiche Kosmetikstudios brauchen mehr als gute Behandlungen - sie brauchen motivierte Mitarbeiter. Führungsstrategien für mehr Erfolg.',
        category: 'Business',
        readTime: '10 min',
        publishDate: '3. Dezember 2024',
        publishedAt: '2024-12-03',
        featured: false,
        image: '/images/blog/mitarbeiterfuehrung.jpg',
    },
    {
        slug: 'hygiene-sicherheit-kosmetikstudio',
        title: 'Hygiene und Sicherheit im Kosmetikstudio: Rechtssicher und professionell',
        excerpt: 'Hygieneverordnungen, Desinfektionsvorschriften und Sicherheitsstandards - alles was du für einen rechtssicheren Studiobetrieb wissen musst.',
        category: 'Recht & Compliance',
        readTime: '12 min',
        publishDate: '28. November 2024',
        publishedAt: '2024-11-28',
        featured: false,
        image: '/images/blog/hygiene-sicherheit.jpg',
    },
    {
        slug: 'zusatzumsatz-kosmetikstudio-produkte',
        title: 'Zusatzumsatz generieren: Der ultimative Guide für Produktverkäufe',
        excerpt: 'Bis zu 40% mehr Umsatz durch cleveren Produktverkauf. Welche Produkte funktionieren und wie du sie erfolgreich verkaufst.',
        category: 'Business',
        readTime: '12 min',
        publishDate: '28. November 2024',
        publishedAt: '2024-11-28',
        featured: false,
        image: '/images/blog/produktverkauf-guide.jpg',
    },
    {
        slug: 'lash-wimpern-kundenbindung',
        title: 'Lash-Kundinnen binden: Wimpernverlängerung und Wiederkehr',
        excerpt: 'Refill-Intervalle, Erinnerungen und persönliche Notizen – so behältst du deine Lash-Kundinnen und füllst den Kalender.',
        category: 'Kundenbindung',
        readTime: '5 min',
        publishDate: '28. November 2024',
        publishedAt: '2024-11-28',
        featured: false,
        image: '/images/blog/lash-kundenbindung.jpg',
    },
    {
        slug: 'saisonales-marketing-beauty-studios',
        title: 'Saisonales Marketing für Beauty-Studios: Das ganze Jahr über erfolgreich',
        excerpt: 'Nutze die Kraft der Jahreszeiten für dein Marketing! Von Frühjahrskuren bis Winterpflege - so planst du saisonale Kampagnen.',
        category: 'Marketing',
        readTime: '11 min',
        publishDate: '25. November 2024',
        publishedAt: '2024-11-25',
        featured: false,
        image: '/images/blog/saisonales-marketing.jpg',
    },
    {
        slug: 'urlaub-vertretung-kosmetikstudio',
        title: 'Urlaub und Vertretung im Kosmetikstudio: So planst du durch',
        excerpt: 'Wer vertritt dich, wer übernimmt Termine, und wie bleiben Kundinnen informiert? Tipps für entspannte Auszeiten.',
        category: 'Business',
        readTime: '4 min',
        publishDate: '22. November 2024',
        publishedAt: '2024-11-22',
        featured: false,
        image: '/images/blog/urlaub-vertretung-studio.jpg',
    },
    {
        slug: 'social-media-marketing-kosmetikstudio',
        title: 'Social Media Marketing für Kosmetikstudios: Instagram & TikTok Strategien',
        excerpt: 'Gewinne neue Kundinnen über Social Media. Bewährte Content-Strategien, die wirklich funktionieren - auch mit wenig Zeit.',
        category: 'Marketing',
        readTime: '9 min',
        publishDate: '20. November 2024',
        publishedAt: '2024-11-20',
        featured: false,
        image: '/images/blog/social-media-marketing.jpg',
    },
    {
        slug: 'sms-erinnerungen-termine-kosmetikstudio',
        title: 'SMS-Erinnerungen für Termine: Warum sie im Studio ankommen',
        excerpt: 'E-Mail oder SMS? Warum viele Kundinnen Erinnerungen per SMS eher lesen und was du bei der Formulierung beachten solltest.',
        category: 'Automatisierung',
        readTime: '4 min',
        publishDate: '18. November 2024',
        publishedAt: '2024-11-18',
        featured: false,
        image: '/images/blog/sms-erinnerungen-termine.jpg',
    },
    {
        slug: 'preisgestaltung-kosmetikbehandlungen',
        title: 'Preisgestaltung im Kosmetikstudio: Was deine Behandlungen wirklich wert sind',
        excerpt: 'Viele Studios verkaufen sich unter Wert. So kalkulierst du deine Preise richtig und kommunizierst den Wert deiner Arbeit.',
        category: 'Business',
        readTime: '7 min',
        publishDate: '15. November 2024',
        publishedAt: '2024-11-15',
        featured: false,
        image: '/images/blog/preisgestaltung-guide.jpg',
    },
    {
        slug: 'terminkalender-kosmetikstudio-effizienz',
        title: 'Effizienter Terminkalender im Kosmetikstudio: So planst du deinen Tag perfekt',
        excerpt: 'Optimiere deinen Terminkalender und steigere die Effizienz um 40%. Professionelle Tipps für bessere Terminplanung, weniger Stress und mehr Umsatz im Kosmetikstudio.',
        category: 'Organisation',
        readTime: '10 min',
        publishDate: '22. Januar 2024',
        publishedAt: '2024-01-22',
        featured: true,
        image: '/images/blog/terminkalender.png',
    },
    {
        slug: 'nachrichtenautomatisierung-kosmetikstudio',
        title: 'Nachrichtenautomatisierung für Kosmetikstudios: 80% weniger No-Shows durch automatische Erinnerungen',
        excerpt: 'Entdecke, wie automatische Terminerinnerungen, Follow-ups und Geburtstagswünsche dein Kosmetikstudio revolutionieren. Reduziere No-Shows um 80% und steigere die Kundenbindung.',
        category: 'Automatisierung',
        readTime: '8 min',
        publishDate: '20. Januar 2024',
        publishedAt: '2024-01-20',
        featured: true,
        image: '/images/blog/no-shows.png',
    },
];
